# Generated by Django 3.2.9 on 2023-01-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_url", models.URLField()),
                ("live_url", models.URLField()),
                ("project_name", models.CharField(max_length=200)),
                ("project_description", models.CharField(max_length=600)),
                ("project_image", models.FileField(upload_to="photo")),
                ("project_id", models.URLField()),
                ("show", models.BooleanField(default=False)),
            ],
        ),
    ]
